name: Build and Deploy Pages

on:
  # push:
  # branches: [master]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      # - name: Checkout Submodules
      #   run: |
      #     git submodule update --init --recursive vendor/assimp
      #     git submodule update --init --recursive vendor/imgui
      #     git submodule update --init --recursive vendor/ImGuizmo
      #     git submodule update --init --recursive vendor/ozz-animation
      #     git submodule update --init --recursive vendor/spdlog
      #     git submodule update --init --recursive vendor/flecs
      #     git submodule update --init --recursive vendor/stb
      #     git submodule update --init --recursive vendor/JoltPhysics
      # - name: Setup Emscripten
      #   uses: mymindstorm/setup-emsdk@v14
      #   with:
      #     version: 4.0.10
      # - name: CMake Configure
      #   run: |
      #     export EMSCRIPTEN=$EMSDK/upstream/emscripten
      #     cmake --preset emscripten-release \
      #       -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      # - name: CMake Build
      #   run: cmake --build build/emscripten-release --parallel
      # - name: Prepare Files
      #   run: |
      #     mkdir -p deploy
      #     cp html/templates/index.html deploy/index.html
      #     cp build/emscripten-release/ReEngine.js deploy/
      #     cp build/emscripten-release/ReEngine.data deploy/
      #     cp build/emscripten-release/ReEngine.wasm deploy/
      #     cp -r Resources deploy/
      - run: |
          mkdir -p deploy
          echo "hello, world" > deploy/index.html
      - id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: deploy
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
